# Generated by Django 3.0.3 on 2020-03-01 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juez',
            name='despacho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='despacho.Despacho'),
        ),
    ]
