# Generated by Django 3.0.3 on 2020-03-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0003_auto_20200301_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juez',
            name='despacho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juezs', to='despacho.Despacho'),
        ),
    ]
