# Generated by Django 3.0.3 on 2020-02-19 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0001_initial'),
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacion',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='cautelar',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='abogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abogado.Abogado'),
        ),
    ]
