# Generated by Django 3.0.3 on 2020-04-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cautelar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partesj',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partesn',
            options={},
        ),
    ]
