# Generated by Django 3.0.5 on 2020-05-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('VALOR', 'valor'), ('EJECUTIVO', 'ejecutivo')], default='VALOR', max_length=9)),
                ('obligacion', models.CharField(choices=[('DAR', 'dar'), ('HACER', 'hacer'), ('NO_HACER', 'no hacer')], default='DAR', max_length=8)),
                ('cuantia', models.CharField(default='minima', max_length=6)),
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso')),
            ],
        ),
    ]
