# Generated by Django 3.0.3 on 2020-02-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_auto_20200218_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='tipo',
            field=models.CharField(choices=[('JURIDICO', 'juridico'), ('EJECUTIVO', 'ejecutivo'), ('OTRO', 'otro')], default='JURIDICO', max_length=30),
        ),
    ]
