# Generated by Django 3.0.5 on 2020-05-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_ejecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutivo',
            name='clase',
            field=models.CharField(choices=[('SINGULAR', 'singular'), ('HIPOTECARIO', 'hipotecario'), ('MIXTO', 'mixto')], default='SINGULAR', max_length=11),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='pretension',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
