# Generated by Django 3.0.3 on 2020-04-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_auto_20200405_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partesj',
            old_name='Proceso',
            new_name='proceso',
        ),
        migrations.RenameField(
            model_name='partesn',
            old_name='Proceso',
            new_name='proceso',
        ),
    ]
