# Generated by Django 3.0.3 on 2020-03-02 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proceso', '0003_auto_20200228_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='abogado',
        ),
        migrations.AddField(
            model_name='proceso',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
