# Generated by Django 3.0.3 on 2020-03-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0004_auto_20200302_1725'),
        ('proceso', '0004_auto_20200302_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='despacho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='despacho.Despacho'),
        ),
    ]
