# Generated by Django 3.0.3 on 2020-03-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0005_proceso_despacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='User',
            new_name='user',
        ),
    ]
