# Generated by Django 3.0.3 on 2020-03-25 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0006_auto_20200306_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partesj',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterModelOptions(
            name='partesn',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterField(
            model_name='partesj',
            name='Proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partesJuridicas', to='proceso.Proceso'),
        ),
        migrations.AlterField(
            model_name='partesn',
            name='Proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partesNaturales', to='proceso.Proceso'),
        ),
    ]
