# Generated by Django 3.0.3 on 2020-03-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0002_auto_20200228_1924'),
        ('proceso', '0007_auto_20200324_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificados',
            new_name='PersonasNotificadas',
        ),
        migrations.AlterModelOptions(
            name='actuacion',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterModelOptions(
            name='cautelar',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'permissions': (('asignar_permisos', 'Asigna permisos sobre el objeto'), ('ver', 'ver'), ('agregar', 'agregar'), ('modificar', 'modificar'), ('eliminar', 'eliminar'))},
        ),
        migrations.CreateModel(
            name='EmpresasNotificadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificado', models.BooleanField(default=False)),
                ('medio', models.CharField(choices=[('EMAIL', 'email'), ('PERSONAL', 'personal'), ('TELEFONO', 'telefono')], default='EMAIL', max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abogado.Empresa')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Notificacion')),
            ],
        ),
    ]
