# Generated by Django 3.0.3 on 2020-03-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0008_auto_20200328_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuacion',
            old_name='Anotacion',
            new_name='anotacion',
        ),
    ]
