# Generated by Django 3.0.3 on 2020-03-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0011_auto_20200328_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasnotificadas',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresasNotificadas', to='proceso.Notificacion'),
        ),
        migrations.AlterField(
            model_name='personasnotificadas',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personasNotificadas', to='proceso.Notificacion'),
        ),
    ]
