# Generated by Django 3.0.3 on 2020-03-29 23:11

import apps.proceso.models.ejecutivo
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0012_auto_20200328_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutivo',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='pretencion',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.proceso.models.ejecutivo.Ejecutivo.pretencion_default, verbose_name='pretencion'),
        ),
    ]
