# Generated by Django 3.0.3 on 2020-03-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0013_auto_20200329_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutivo',
            name='id',
        ),
        migrations.AlterField(
            model_name='ejecutivo',
            name='proceso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proceso.Proceso'),
        ),
    ]
