# Generated by Django 3.0.5 on 2020-05-11 21:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('fijo', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=60)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('fijo', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=60)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('documento', models.FloatField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(default='555', max_length=50)),
                ('especialidad', models.CharField(default='555', max_length=50)),
                ('nacimiento', models.DateField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
