# Generated by Django 3.0.3 on 2020-02-17 21:05

import apps.abogado.models.empresa
import apps.abogado.models.persona
import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField(default=apps.abogado.models.persona.Persona.contact_default, verbose_name='ContactInfo')),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField(default=apps.abogado.models.empresa.Empresa.contact_default, verbose_name='ContactInfo')),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('documento', models.FloatField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(default='555', max_length=50)),
                ('especialidad', models.CharField(default='555', max_length=50)),
                ('nacimiento', models.DateField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
