# Generated by Django 3.0.5 on 2020-05-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fijo',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
