# Generated by Django 3.0.3 on 2020-02-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abogado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='actividad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
